DjangoWebApplication/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'myapp/', include('myapp.urls')),

]

myapp/urls.py
from django.conf import settings
from django.urls import path, include
from myapp import views
from django.contrib.auth.views import LogoutView
from django.contrib.auth.views import LoginView

app_name = 'myapp'

urlpatterns = [
    path(r'home', views.index, name='index'),
    path(r'about', views.about, name='about'),
    path(r'', views.index, name='index'),
    path(r'logged', views.user_login, name='login'),
    path(r'register', views.register, name='register'),
    path(r'<int:cat_no>', views.detail, name='detail'),
    path(r'products', views.products, name='products'),
    path(r'products/<int:prod_id>', views.productdetail, name='product_detail'),
    path(r'placeorder', views.place_order, name='place_order'),
    path(r'myorders', views.my_orders, name='my_order'),
    # path(r'logout', views.logout, name='logout'),
    path(r'logout/', LogoutView.as_view(next_page='myapp:index'), name='logout'),
    path(r'forgot', views.forgot_password, name='forgot')
]

myapp/models.py
from decimal import Decimal

from django.core.exceptions import ValidationError
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.contrib import admin
from django.utils import timezone


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)
    warehouse = models.CharField(max_length=200, default='xyz')

    def __str__(self):
        return self.name


def validate_stock(value):
    if 0 <= value <= 1000:
        return value
    else:
        raise ValidationError("The value is not in the given threshold of the stock parameters")


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField(default=100, validators=[validate_stock])
    available = models.BooleanField(default=True)
    description = models.TextField(blank=True)
    interested = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

    def refill(self):
        self.stock += 100


class Client(User):
    PROVINCE_CHOICES = [
        ('AB', 'Alberta'),
        ('MB', 'Manitoba'),
        ('ON', 'Ontario'),
        ('QC', 'Quebec'), ]
    shipping_address = models.CharField(max_length=300, null=True, blank=True)
    city = models.CharField(max_length=20, default='Windsor')
    province = models.CharField(max_length=2, choices=PROVINCE_CHOICES, default='ON')
    interested_in = models.ManyToManyField(Category)
    company = models.CharField(max_length=200, blank=True)


    def __str__(self):
        return self.first_name

    def get_interest(self):
        return ", ".join([i.name for i in self.interested_in.all()])


class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    num_units = models.PositiveIntegerField(default=0)
    order_status_choices = [
        (0, 'Order Cancelled'),
        (1, 'Order Placed'),
        (2, 'Order Shipped'),
        (3, 'Order Delivered')]
    order_status = models.PositiveIntegerField(choices=order_status_choices, default=1)
    status_date = models.DateField(default=datetime.date.today)

    def __str__(self):
        return 'Product: %s, Client: %s, Units: %s' % (self.product.name, self.client.first_name, self.num_units)

    def printx(self):
        return self.product.price * self.num_units

    @admin.display(description='Order Total')
    def order_total(self):
        return self.product.price * self.num_units

myapp/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.forms import TextInput, PasswordInput
from django.forms.utils import ErrorList

from myapp.models import Order, Client


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['client', 'product', 'num_units']
        labels = {
            'num_units': 'Quantity',
            'client': 'Client Name'
        }
        widgets = {
            'client': forms.RadioSelect()
        }


class InterestForm(forms.Form):
    CHOICES = [(1, 'YES'), (0, 'NO')]
    interested = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICES)
    quantity = forms.IntegerField(min_value=1, initial=1)
    comments = forms.CharField(widget=forms.Textarea, label='Additional Comments', required=False)


class UserLogin(AuthenticationForm):
    username = forms.CharField(widget=TextInput(attrs={"placeholder": "Username", "type": "text",
                                                       "class": "form-control form-control-user", "id": "id_username"}))
    password = forms.CharField(widget=PasswordInput(attrs={"placeholder": "Password", "type": "password",
                                                           "class": "form-control form-control-user",
                                                           "id": "id_password"}))


class RegisterForm(UserCreationForm):
    class Meta:
        model = Client
        fields = ['first_name', 'last_name', 'email', 'username', 'company', 'interested_in', 'shipping_address',
                  'province', 'city']


class ForgotPassword(forms.Form):
    username = forms.CharField(widget=TextInput(attrs={"placeholder": "Username", "type": "text",
                                                       "class": "form-control form-control-user", "id": "id_username"}))

myapp/views.py
from datetime import datetime

from django import forms
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .forms import OrderForm, InterestForm, UserLogin, RegisterForm, ForgotPassword
from .models import Category, Product, Client, Order
from django.shortcuts import render

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User


# Create your views here.
# def detail(request, cat_no):
#     category = get_object_or_404(Category, id=cat_no)
#     prod_list = Product.objects.filter(category__id=cat_no).order_by('id')
#     response = HttpResponse()
#     text = '<p>' + 'Warehouse Location: ' + str(category) + '</p>'
#     response.write(text)
#     text = '<p>' + 'List of products: ' + '</p>'
#     response.write(text)
#     for product in prod_list:
#         text = '<p>' + str(product.id) + ': ' + str(product) + ' ' + str(product.price) + '</p>'
#         response.write(text)
#     return response


def index(request):
    if request.user.username != '':
        request.session.set_expiry(3600)
        cat_list = Category.objects.all().order_by('id')[:10]
        msg = ''

        if 'last_login' not in request.session:
            request.session['last_login'] = User.objects.get(username=request.user.username). \
                last_login.strftime('%y-%m-%d %a %H:%M:%S')
            msg = '<span class="text-custom-two fw-bold">Last Login: </span> More than one hour ago'
        else:
            msg = '<span class="text-custom-two fw-bold">Last Login: </span>' + request.session['last_login']
    # return render(request, 'myapp/index0.html', {'cat_list': cat_list}) commented out as requested in lab 6, part 3
    else:
        cat_list = Category.objects.all().order_by('id')[:10]
        msg = ''

    return render(request, 'myapp/index.html', {'msg': msg, 'cat_list': cat_list, 'user': request.user})


def about(request):
    msg = ''
    request.session.set_expiry(300)

    if 'about_visits' in request.session:
        request.session['about_visits'] += 1
    else:
        request.session['about_visits'] = 0
    msg = request.session['about_visits']
    return render(request, 'myapp/about.html', {'msg': msg})

    # response = HttpResponse()
    # text = '<p>' + 'This is an Online Store APP.' + '</p>'
    # response.write(text)
    # return response


def detail(request, cat_no):
    category = get_object_or_404(Category, id=cat_no)
    prod_list = Product.objects.filter(category__id=cat_no).order_by('id')
    return render(request, 'myapp/detail.html', {'prod_list': prod_list, 'category': category})

    # response = HttpResponse()
    # text = '<p>' + 'Warehouse Location: ' + str(category) + '</p>'
    # response.write(text)
    # text = '<p>' + 'List of products: ' + '</p>'
    # response.write(text)
    # for product in prod_list:
    #    text = '<p>' + str(product.id) + ': ' + str(product) + ' ' + str(product.price) + '</p>'
    #    response.write(text)
    # return response


def products(request):
    prodlist = Product.objects.all().order_by('id')[:10]
    return render(request, 'myapp/products.html', {'prodlist': prodlist})


def place_order(request):
    msg = ''
    prod_list = Product.objects.all()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if order.num_units < order.product.stock:
                order.product.stock -= order.num_units
                order.product.save()
                order.save()
                msg = 'Your order has been placed successfully.'
            else:
                msg = 'We do not have sufficient stock to fill your order.'
            return render(request, 'myapp/order_response.html', {'msg': msg})
    else:
        form = OrderForm()
    return render(request, 'myapp/placeorder.html', {'form': form, 'msg': msg, 'prod_list': prod_list})


def productdetail(request, prod_id):
    prod = Product.objects.filter(id=prod_id).get()
    if request.method == 'POST':
        form = InterestForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['interested'] == '1':
                prod.interested += 1
            prod.save()
            return HttpResponseRedirect('/myapp/')
    else:
        form = InterestForm()
    return render(request, 'myapp/product_detail.html', {'form': form, 'prod': prod})


def user_login(request):
    form_class = UserLogin
    form = form_class(request.POST)
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                user_obj = User.objects.get(username=username)
                num = request.session.get('login')
                if num is not None:
                    request.session['login'] = 0
                    return HttpResponseRedirect(reverse('myapp:my_order'))
                else:
                    return HttpResponseRedirect(reverse('myapp:index'), {'user': user_obj})
                # return HttpResponseRedirect(reverse('myapp:myorders', {'username': username))
                # return render(request, 'myapp/index.html', {'user': user_obj})
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        return render(request, 'myapp/login.html', {'form': form})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('myapp:index'))


def my_orders(request):
    msg = ''
    order_list = []
    if request.user.username == '':
        request.session['login'] = 1
        user_login(request)
        form_class = UserLogin
        form = form_class(request.POST)
        return render(request, 'myapp/login.html', {'form': form})
    else:
        if Client.objects.filter(username=request.user.username).exists():
            if Order.objects.filter(client__username=request.user.username).exists():
                order_list = Order.objects.filter(client__username=request.user.username)
                msg = 'User Found'
            else:
                msg = 'You currently have no orders.'
        else:
            msg = 'You are not a registered client.'
        return render(request, 'myapp/myorders.html', {'msg': msg, 'order': order_list})


def register(request):
    form_class = RegisterForm
    if request.FILES:
        form = form_class(request.POST, request.FILES)
    else:
        form = form_class(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            user = form.save()
            return HttpResponseRedirect(reverse('myapp:login'))
        else:
            return render(request, 'myapp/register.html', {'form': form, 'msg': 'Form is incorrect'})
    else:
        form = RegisterForm()
    return render(request, 'myapp/register.html', {'form': form})


def forgot_password(request):
    user = ''
    form = ForgotPassword(request.POST)
    if request.method == 'POST':
        username = request.POST['username']
        if Client.objects.filter(username=username).exists():
            user = Client.objects.get(username=username)
            password = Client.objects.make_random_password(length=10)
            user.set_password(password)
            user.save()
            msg = 'Your password has been changed. Your new Password is: ' + password
            status = send_mail('Password Changed', msg, None, [user.email], fail_silently=False)
            response_msg = ''
            if status == 1:
                response_msg = 'New password is sent to your registered email.'
            else:
                response_msg = 'Password sending failed!'
            return render(request, 'myapp/forgot_password_response.html',
                          {'msg': response_msg})
    else:
        return render(request, 'myapp/forgot_password.html', {'form': form})
    return render(request, 'myapp/forgot_password_response.html', {'msg': 'Invalid username'})

myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}

{% block myhdg %}

    Hello {{ user.username }}

{% endblock %}

{% block title %}

    About

{% endblock %}

{% block body_block %}

    <div class="description my-5">
        <h3>This is an Online Store Application.</h3>
    </div>
    <div class="about-container">
        <p>
            <span class="text-custom-two fw-bold">URL Namespaced Link:</span>
            <a href="{% url 'myapp:index' %}">Index page</a>
        </p>
        <p>
            <span class="text-custom-two fw-bold">Hardcoded Link:</span>
            <a href="/myapp">Index page</a>
        </p>
        <p>
            <span class="text-custom-two fw-bold">Number of Visits to this page:</span>
            {{ msg }}
        </p>
    </div>
{% endblock %}

myapp/templates/myapp/about0.html
<!DOCTYPE html>
<html lang="en">
<head lang="en">
    <meta charset="UTF-8">
    <title>Online Store APP</title>
</head>
<body>

    <h1>This is an Online Store Application.</h1>
    <p>URL Namespaced Link: <a href="{% url 'myapp:index' %}">Index page</a></p>
    <p>Hardcoded Link: <a href="/myapp">Index page</a></p>

</body>
</html>

myapp/templates/myapp/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Online Store APP - {% block title %}Welcome!{% endblock %}</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" >
        <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}"/>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    </head>
    <body class="bg-custom">
        <div class="container text-white">
            <div class="col-12">
                <div class="header my-5">
                    <div class="title text-custom-two text-capitalize text-center my-3">
                        <h1>{% block myhdg %} Hello {{ user.username }} {% endblock %}</h1>
                    </div>
                    {% block body_block %}*** {% endblock %}
                </div>
            <hr />
            <div class="footer text-center py-3">
                <div class="main-links">
                    <a class="mx-2" href="{% url 'myapp:about' %}">About</a>
                    <span>|</span>
                    <a class="mx-2" href="{% url 'myapp:products' %}">Products</a>
                    <span>|</span>
                    <a class="mx-2" href ="{% url 'myapp:index' %}">Home</a>
                </div>
                {% if user.username == '' %}
                <div class="sub-links">
                    <a class="mx-2" href ="{% url 'myapp:register'%}">Register</a>
                    <span>|</span>
                    <a class="mx-2" href="{% url 'myapp:login' %}">Login</a>
                    <span>|</span>
                    <a class="mx-2" href="{% url 'myapp:my_order' %}">My Orders</a>
                {% else %}
                    <a class="mx-2" href="{% url 'myapp:my_order' %}">My Orders</a>
                    <span>|</span>
                    <a class="mx-2" href="{% url 'myapp:logout' %}">Logout</a>
                </div>
                {% endif %}

                <div class="copyrights text-center py-3">&copy; Matrix 2022 | All Rights Reserved</div>
            </div>
        </div>
    </body>
</html>

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}

{% block myhdg %}

    Hello {{ user.username }}

{% endblock %}

{% block title %}

    Detail

{% endblock %}

{% block body_block %}

    {% if category %}
        <div class="category-main">
            <p class="mb-0">
                <span class="text-custom-two fw-bold">Category: </span>
                {{ category.name}}
            </p>
            <p>
                <span class="text-custom-two fw-bold">Warehouse: </span>
                {{ category.warehouse }}
            </p>
        </div>
    {% endif %}

    {% if prod_list %}
        <h4 class="text-decoration-underline my-4">List of products</h4>
        <ol>
            {% for prod in prod_list %}
                <li><a href="{% url 'myapp:product_detail' prod.id %}">{{ prod }} - {{ prod.price }} <span class="fst-italic">(Id: {{ prod.id}})</span></a></li>
            {% endfor %}
        </ol>

        {#<p><a href="{% url 'myapp:index' %}">Index page</a></p>#}
    {% else %}
        <strong>There are no products available for this category!</strong>

        {#<p><a href="{% url 'myapp:index' %}">Index page</a></p>#}
    {% endif %}

{% endblock %}

myapp/templates/myapp/detail0.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Online Store APP</title>
</head>
<body>

    {% if category %}
        <h1>Category: {{ category.name}}</h1>
        <h1>Warehouse: {{ category.warehouse }} </h1>
    {% endif %}

    {% if prod_list %}
        <h1>List of products:</h1>
        <ol>
            {% for prod in prod_list %}
            <li> {{ prod.id}}: {{ prod }}- {{ prod.price }} </li>
            {% endfor %}
        </ol>

        <p><a href="{% url 'myapp:index' %}">Index page</a></p>
    {% else %}
        <strong>There are no products available for this category!</strong>

        <p><a href="{% url 'myapp:index' %}">Index page</a></p>
    {% endif %}

</body>
</html>

myapp/templates/myapp/forgot_password.html
{% extends 'myapp/base.html' %}

{% block title %}

    Forgot Password

{% endblock %}

{% block myhdg %}

{% endblock %}

{% block body_block %}


    {% if msg %}
        {{ msg }}
    {% endif %}

    <div class="col-4 offset-4 p-5">

        <div class="title text-center mb-4">
        <h3 class="text-custom-two">Forgot Password</h3>
        </div>

        <div class="form-container">

            <form method="post">

                {% csrf_token %}
                {{ form }}
                <div class="form-button my-2 text-center">
                    <button class="btn btn-light" type="submit" value="Submit">Submit</button>
                </div>
            </form>

        </div>

    </div>




{#    #}
{#    <h2>Forgot Password</h2>#}
{##}
{#    {% if msg %}#}
{##}
{#    {{ msg }}#}
{##}
{#    {% endif %}#}
{##}
{#    <form method="post">#}
{#        {% csrf_token %}#}
{#        {{ form }}#}
{#        <button class="btn btn-primary" type="submit" value="Submit">Submit</button>#}
{#    </form>#}

{% endblock %}

myapp/templates/myapp/forgot_password_response.html
{% extends 'myapp/base.html' %}

{% block myhdg %}

{% endblock %}

{% block title %}

    Response

{% endblock %}

{% block body_block %}

    <p>Response: {{ msg }}</p>
    <div class="anchor-container mt-5 text-center">
        Go back to <a href="forgot">Forgot Password</a> page.
    </div>


{% endblock %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block myhdg %}

    {% if user %}
        Hello {{ user.username }}
        <img src="{{ user.image.url }}" style="max-height:300px" />
    {% endif %}

{% endblock %}

{% block body_block %}

    {% if cat_list %}
        <div class="sub-container">
            <div class="title mb-4">
                <h2 class="text-decoration-underline">List of Categories</h2>
            </div>
            <div class="list">
                <ol>
                    {% for cat in cat_list %}
                        <li> <a href="{% url 'myapp:detail' cat.id %}">{{ cat.name}}</a> </li>
                    {% endfor %}
                </ol>
            </div>
        </div>
        {#<p><a href="{% url 'myapp:about' %}">About page</a></p>#}
    {% else %}
        <div class="none-found text-center">
            <p class="fw-bold">There are no available categories.</p>
        </div>
        {#<p><a href="{% url 'myapp:about' %}">About page</a></p>#}
    {% endif %}

    {% if msg %}
        <p class="my-5 text-end">{{ msg | safe }}</p>
    {% endif %}

{% endblock %}

myapp/templates/myapp/order_response.html
{% extends 'myapp/base.html' %}

{% block myhdg %}
    Hello {{ user.username }}
{% endblock %}

{% block body_block %}
    {% if msg %}
        <div class="fw-bold text-center">
            <p>{{ msg }}</p>
        </div>
    {% endif %}
{% endblock %}

myapp/templates/myapp/place_order.html
{% extends 'myapp/base.html' %}

{% block myhdg %}

Hello {{ user.username }}

{% endblock %}

{% block body_block %}
{% if prod_list %}
<h2>Place Order</h2>

<form method="post">
    {% csrf_token %}
    {{ form }}
    <button class="btn btn-primary" type="submit" value="Submit">Submit</button>
</form>

{% endif %}
{% endblock %}

myapp/templates/myapp/placeorder.html
{% extends 'myapp/base.html' %}

{% block myhdg %}

    Hello {{ user.username }}

{% endblock %}

{% block body_block %}
    {% if prod_list %}
        <div class="sub-container">
            <div class="title mb-4">
                <h2 class="text-decoration-underline">All Products</h2>
            </div>
            <div class="list">
                <ol>
                    {% for prod in prod_list %}
                    <li><a href="{% url 'myapp:product_detail' prod.id %}">{{ prod.name}}</a></li>
                    {% endfor %}
                </ol>
            </div>
        </div>
    {% endif %}


     <div class="col-4 offset-4 p-5">

        <div class="title text-center mb-4">
            <h3 class="text-custom-two">Place Order</h3>
        </div>

        <div class="form-container">
            <form method="post">
                {% csrf_token %}
                {{ form }}
                <div class="form-button my-2 text-center">
                    <button class="btn btn-light" type="submit" value="Submit">Submit</button>
                </div>
            </form>
        </div>

    </div>

{% endblock %}

myapp/templates/myapp/product_detail.html
{% extends 'myapp/base.html' %}

{% block myhdg %}

    Hello {{ user.username }}

{% endblock %}

{% block body_block %}

    <p class="mb-0">
        <span class="text-custom-two fw-bold">Product Name:</span>
        <span>{{ prod.name }}</span>
    </p>
    <p class="mb-0">
        <span class="text-custom-two fw-bold">Interested:</span>
        <span>{{ prod.interested }}</span>
    </p>
    <p class="mb-0">
        <span class="text-custom-two fw-bold">Price:</span>
        <span>{{ prod.price }}</span>
    </p>
    <p class="mb-0">
        <span class="text-custom-two fw-bold">Available:</span>
        <span>
            {% if prod.available %}
                Yes
            {% else %}
                No
            {% endif %}
        </span>
    </p>

    <div class="col-4 offset-4 p-5">

        <div class="title text-center mb-4">
            <h3>Interested in <span class="text-custom-two">{{ prod.name }}</span>?</h3>
        </div>

        <div class="form-container">
            <form method="post">
                {% csrf_token %}
                {{ form }}
                <div class="form-button my-2 text-center">
                    <button class="btn btn-light" type="submit" value="Submit">Submit</button>
                </div>
            </form>
        </div>

    </div>

{##}
{#<h2>Interested in {{ prod.name }}?</h2>#}
{##}
{#<form method="post">#}
{#    {% csrf_token %}#}
{#    {{ form }}#}
{#    <button class="btn btn-primary" type="submit" value="Submit">Submit</button>#}
{#</form>#}

{% endblock %}

myapp/templates/myapp/products.html
{% extends 'myapp/base.html' %}

{% block myhdg %}

    Hello {{ user.username }}

{% endblock %}

{% block body_block %}
    {% if prodlist %}
        <div class="sub-container">
            <div class="title mb-4">
                <h2 class="text-decoration-underline">Available products</h2>
            </div>
            <div class="list">
                <ol>
                    {% for prod in prodlist %}
                        {% if prod.available %}
                            <li><a href="{% url 'myapp:product_detail' prod.id %}"> {{ prod }} - {{ prod.price }}</a></li>
                        {% endif %}
                    {% endfor %}
                </ol>
            </div>
        </div>

    {% else %}
        <p class="fw-bold text-center">There are no available products!</p>
    {% endif %}

    <div clas="btn-container">
        <a class="btn btn-light" href="{% url 'myapp:place_order' %}">Place Order</a>
    </div>
{% endblock %}

myapp/templates/myapp/register.html
{% extends 'myapp/base.html' %}

{% block title %}

    Register

{% endblock %}

{% block myhdg %}

{% endblock %}

{% block body_block %}


    {% if msg %}
        {{ msg }}
    {% endif %}

    <div class="col-6 offset-3 p-2">

        <div class="title text-center mb-4">
        <h3 class="text-custom-two">Register</h3>
        </div>

        <div class="form-container">

            <form method="post" enctype="multipart/form-data">

                {% csrf_token %}
                {{ form }}
                <div class="form-button my-2 text-center">
                    <button class="btn btn-light" type="submit" value="Submit">Submit</button>
                </div>
            </form>

        </div>

    </div>

{#    <h2>Register</h2>#}
{#<form method="post" enctype="multipart/form-data">#}
{#    {% csrf_token %}#}
{#    {{ form }}#}
{#    <button class="btn btn-primary" type="submit" value="Submit">Submit</button>#}
{#</form>#}

{% endblock %}